---
- hosts: localhost
  become: True
  become_user: root
  become_exe: "sudo su -"
  
  tasks:
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: newapp
        image: "zahed/newapp:0.0.1 "
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
